### ISSUE TITLE
Tracking code twice

### ISSUE THREAD

**Issue by msebald** [candango/matomo_analytics_rc#1]
I noticed that the tracking code is there twice on the login page. When logged in I only see it once.

**Comment by piraz** [comment]
What is the version of roundcube you are using @msebald?

**Comment by msebald** [comment]
@piraz it is the latest version 1.5.0 and the login page is running with the Elastic theme.

**Comment by piraz** [comment]
On it.

**Comment by piraz** [comment]
Just double checking, do you have the old crc_matomo_analytics that was renamed to matomo_analytics_rc enabled?

I'm running 1.5.0 and cannot reproduce the issue. I can get twice all the time when both are enabled.

I don't think this is your case. Maybe we could arrange to see what's going on in your environment.

Let's avoid to post your stuff here. Maybe your conf with real info obfuscated or a list of plugins enabled currently.

**Comment by msebald** [comment]
Sorry for replying that late. Active plugins are these:

```
$config['plugins'] = [
        'jqueryui',
        'dovecot_impersonate',
        'ispconfig3_account',
        'ispconfig3_autoreply',
        'ispconfig3_pass',
        'ispconfig3_spam',
        'ispconfig3_fetchmail',
        'ispconfig3_filter',
        'ispconfig3_forward',
        'ispconfig3_wblist',
        'archive',
        'zipdownload',
        'filesystem_attachments',
        'help',
        'show_additional_headers',
        'authres_status',
        'emoticons',
        'rc_bugheader',
        'matomo_analytics_rc',
        'removeattachments',
        'lastlogin',
        'twofactor_gauthenticator',
        'html5_notifier',
        'persistent_login',
        'gravatar',
        'new_user_autosubscribe',
        'carddav',
        'markasjunk',
        'contextmenu',
        'contextmenu_folder',
        'listcommands',
        'message_highlight',
        'globaladdressbook',
        'ident_switch',
        'attachment_reminder',
        'identity_select',
        'new_user_dialog',
        'subscriptions_option',
        'vcard_attachments',
        'enigma',
        'rc_smime',
        'thunderbird_labels',
        'account_details',
        'roundcube_impress',
];
```

**Comment by piraz** [comment]
Is it only this plugin that is repeating?

The roundcube_impress seems to be adding a footer for elastic:

https://gitlab.com/takerukoushirou/roundcube-impress/-/blob/main/skins/elastic/templates/page.html#L15

I'll start with this one, seems to be affecting the loging page right?

**Comment by msebald** [comment]
You're right. Without roundcube_impress I only see the Matomo code once. And yes, I noticed this on the login page.

Hm, do you need to fix that or the guy who is maintaining roundcube_impress?

**Comment by piraz** [comment]
All that we do here is print a footer:

https://github.com/candango/matomo_analytics_rc/blob/master/matomo_analytics_rc.php#L89

Do we have a double footer or just the tracking code is repeating?

Funny that classic has no footer:

https://gitlab.com/takerukoushirou/roundcube-impress/-/blob/main/skins/classic/templates/page.html

Larry and elastic has. I can see the double tracking here on my side. I'll just check what could be the issue so we can pinpoint where the fix should be applied.

**Comment by piraz** [comment]
Changing the template in their side won't make a dent. I can see me as part of the problem here because the plugin is running twice.

If somebody run a plugin like that we should be able to tell if the code was already processed and it is possible:

```
<a class="impress" href="?_task=login&_impress=1">
  Impress <=== SEE IMPRESS HERE!!!!
</a>
		</div>
	</form>
</div>

<noscript>
	<p class="noscriptwarning">Warning: This webmail service requires Javascript! In order to use it please enable Javascript in your browser's settings.</p>
</noscript>


</div>



<div id="messagestack"></div>
<!-- Matomo -->
<script type="text/javascript">      V=========== Just one tracking code!!! :)
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://matomo.somewere.net/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '9999']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
<script>
$(function() {
rcmail.init();
});
</script>
```

I'll polish the solution later and you can get the issue solved.

**Comment by piraz** [comment]
On package list @msebald: https://packagist.org/packages/candango/matomo_analytics_rc#0.3

Cheers. Please let me know if you need further help.

**Comment by msebald** [comment]
@piraz thank you, looks great. The code is only there once now. :-)
